import json
import re
from typing import Any, Dict, List

from app.agents.agent_state import AgentState
from app.agents.base_agent import BaseAgent
from app.llm.llm_client import LLMClient


class CriticAgent(BaseAgent):
    """
    Critic Agent — Node 4 of 4 in the KnowGen LangGraph workflow.

    Position in graph: Supervisor → Retriever → Generator → **[CRITIC]** → END

    Mission:
        Act as the quality assurance and final evaluation node that reviews the
        draft answer produced by the Generator. It assesses quality against
        retrieved documents, validates format, and determines if the answer
        meets required standards. The Critic also gates iterative refinement
        through revision feedback.

    Responsibilities:
        1. Format Validation (Priority 1) — Verify output follows correct format
           based on task type (QA vs QUIZ).
        2. Relevance Check — Ensure answer directly addresses user query.
        3. Factual Accuracy — Validate claims against retrieved documents.
        4. Completeness Evaluation — Check all key aspects are covered.
        5. Coherence Review — Assess clarity, grammar, logical flow.
        6. Citation Grounding — Trace references back to documents.
        7. Task-Specific Quality — Apply task-specific evaluation criteria.
        8. Issue Identification — Flag critical vs minor problems.
        9. Accept/Reject Decision — Recommend finalization or revision.

    Reads from AgentState:
        - user_query (str): Original user input.
        - draft (str): Answer generated by Generator.
        - task_type (str): "qa" | "quiz".
        - retrieved_docs (List[Document]): Evidence documents.
        - evidence_summary (List[str]): Key facts from documents.
        - revision_count (int): Number of revisions so far.

    Writes to AgentState:
        - critique (dict): Detailed evaluation with all scores and feedback.
        - revision_required (bool): Whether revision is needed.
        - revision_count (int): Incremented if revision needed.
        - final_answer (str): Draft answer or empty if revision needed.

    Failure behaviour:
        If the LLM response cannot be parsed as valid JSON, the node returns
        a safe fallback with default scores and requests revision.
    """

    name = "critic"

    # Scoring thresholds
    RELEVANCE_WEIGHT = 0.2
    ACCURACY_WEIGHT = 0.25
    COMPLETENESS_WEIGHT = 0.2
    COHERENCE_WEIGHT = 0.2
    FORMAT_WEIGHT = 0.15
    OVERALL_THRESHOLD = 0.75
    MAX_REVISIONS = 2

    SYSTEM_PROMPT = """
        # Role
        You are the Chief Quality Assurance (Critic) Agent of the KnowGen multi-agent system. You are fully bilingual (English & Vietnamese) and an expert evaluator of academic content. Your job is to assess the quality, accuracy, and completeness of generated answers against a knowledge base.

        # Context
        You are reviewing a draft answer that was generated based on:
        1. A user query
        2. Retrieved documents from a FAISS knowledge base
        3. Extracted evidence summaries

        Your task is to evaluate whether the draft answer is accurate, complete, relevant, and ready for final output. If the answer has issues, you provide detailed feedback for revision.

        # Task
        For each draft answer, perform the following:
        1. **Format Validation** (First Priority):
           - For QA: Check structure (title, intro, body sections with headings, conclusion), formatting consistency, code blocks, lists.
           - For QUIZ: Check MCQ format (Q + 4 options A/B/C/D + answer key + explanation for each).
           - Identify format errors and flag as "format_valid": true/false.
        2. **Relevance Check**: Does the answer directly address the user's question?
        3. **Factuality Verification**: Are all claims supported by the retrieved documents?
        4. **Hallucination Detection**: Are there any unsupported assertions or false claims?
        5. **Completeness Assessment**: Are all key aspects of the question covered?
        6. **Language & Clarity Review**: Is the text grammatically correct, clear, and coherent?
        7. **Evidence Grounding**: Can claims be traced back to specific retrieved documents?
        8. **Task-Specific Validation**:
           - For QA: Is the answer concise, well-structured, and directly answers the question?
           - For QUIZ: Are questions valid, unambiguous, and based on document content?

        # Input Data
        You will receive:
        - user_query: Original user question
        - task_type: "qa" or "quiz"
        - draft: The generated answer to review
        - retrieved_docs: List of document chunks used for generation
        - evidence_summary: Key facts extracted from documents

        # Scoring Rubric
        - Relevance (0.0-1.0): How directly does the answer address the query?
        - Accuracy (0.0-1.0): Are claims factually correct and document-grounded?
        - Completeness (0.0-1.0): Are all major aspects of the question covered?
        - Coherence (0.0-1.0): Is the answer clear, well-organized, and grammatically correct?
        - Format (0.0-1.0): Does the answer follow the correct structural format for its task type?
        - Overall: Average of the five scores

        # Output
        Return strictly valid JSON only, using this schema:
        {
          "relevance_score": 0.0-1.0,
          "accuracy_score": 0.0-1.0,
          "completeness_score": 0.0-1.0,
          "coherence_score": 0.0-1.0,
          "format_score": 0.0-1.0,
          "overall_score": 0.0-1.0,
          "is_acceptable": true | false,
          "format_valid": true | false,
          "format_issues": ["Issue 1", "Issue 2"],
          "critical_issues": ["Issue 1", "Issue 2"],
          "minor_issues": ["Issue 1", "Issue 2"],
          "strengths": ["Strength 1", "Strength 2"],
          "feedback": "Detailed critique, specific problems identified, and recommendations for improvement (if needed)",
          "revision_required": true | false,
          "revision_focus": "If revision needed: specific areas to focus on (e.g., 'Fix format structure', 'Add more examples', 'Fix hallucinations about...', 'Clarify section on...')"
        }

        # Constraints
        - Think step by step internally, but present findings objectively.
        - Be specific: reference actual text from the draft and retrieved documents.
        - **Format Check is CRITICAL**: If format_valid = false, set is_acceptable = false immediately.
        - Identify CRITICAL issues (must fix) vs MINOR issues (nice to have).
        - If overall_score < 0.75 OR format_valid = false, set is_acceptable = false and revision_required = true.
        - Format issues should be clearly listed in format_issues array for Generator to fix.
        - Do not output markdown.
        - Do not output any text outside the JSON.
        - Be fair but rigorous: answers must meet academic standards for accuracy, completeness, AND proper formatting.

        # Language
        Respond in the same language as the user query when possible (English or Vietnamese). For mixed-language content, maintain consistency with the original draft.
    """

    def __init__(self):
        super().__init__()
        self.llm_client = LLMClient()

    def run(self, state: AgentState) -> Dict[str, Any]:
        """
        Execute the Critic logic on the current AgentState.

        Steps:
            1. Extract inputs from state (user_query, draft, task_type, etc.)
            2. Build comprehensive prompt with context from retrieved docs
            3. Send to LLM for evaluation (scoring, issues, feedback)
            4. Parse JSON response
            5. Apply revision logic (format gate, score threshold, revision count)
            6. Return updated state dict

        On parse failure, returns fallback state requesting revision.
        """
        user_query = state.get("user_query", "")
        draft = state.get("draft", "")
        task_type = state.get("task_type", "qa")
        retrieved_docs = state.get("retrieved_docs", [])
        evidence_summary = state.get("evidence_summary", [])
        revision_count = state.get("revision_count", 0)

        # Build comprehensive prompt with context
        prompt = self._build_evaluation_prompt(
            user_query=user_query,
            draft=draft,
            task_type=task_type,
            retrieved_docs=retrieved_docs,
            evidence_summary=evidence_summary,
        )

        # Send to LLM for evaluation
        response = self.llm_client.generate_response(prompt)
        response_text = response.content if hasattr(response, "content") else str(response)

        # Parse JSON response
        parsed = self._parse_json(response_text)

        if parsed:
            critique = parsed
        else:
            self.logger.error(f"Failed to parse critic JSON. Raw: {response_text}")
            critique = self._fallback_critique()

        # Apply revision logic
        format_valid = critique.get("format_valid", False)
        overall_score = critique.get("overall_score", 0.0)
        is_acceptable = critique.get("is_acceptable", False)

        # Decision logic
        revision_required = False
        final_answer = ""

        if not format_valid:
            # Format errors are CRITICAL - always request revision
            revision_required = True
            is_acceptable = False
            self.logger.info(f"Format validation failed - revision required")
        elif overall_score < self.OVERALL_THRESHOLD:
            revision_required = True
            is_acceptable = False
            self.logger.info(f"Overall score {overall_score:.2f} below threshold {self.OVERALL_THRESHOLD} - revision required")
        elif not is_acceptable:
            revision_required = True
            is_acceptable = False
            self.logger.info(f"Critique marked answer as unacceptable - revision required")

        # Check if max revisions exceeded
        if revision_count >= self.MAX_REVISIONS:
            self.logger.warning(f"Max revisions ({self.MAX_REVISIONS}) reached - accepting answer")
            revision_required = False
            final_answer = draft

        # If no revision needed, finalize answer
        if not revision_required:
            final_answer = draft
            self.logger.info(f"Answer accepted - finalizing")

        return {
            "critique": critique,
            "revision_required": revision_required,
            "revision_count": revision_count + 1 if revision_required else revision_count,
            "final_answer": final_answer,
        }

    def _build_evaluation_prompt(
        self,
        user_query: str,
        draft: str,
        task_type: str,
        retrieved_docs: List[Any],
        evidence_summary: List[str],
    ) -> str:
        """Build comprehensive evaluation prompt with context."""
        # Format retrieved docs for context
        docs_context = self._format_docs_context(retrieved_docs)

        # Format evidence summary
        evidence_context = "\n".join([f"- {evidence}" for evidence in evidence_summary[:5]])

        prompt = f"""{self.SYSTEM_PROMPT}

# Evaluation Context

**User Query:**
{user_query}

**Task Type:** {task_type.upper()}

**Draft Answer:**
{draft}

**Retrieved Documents Context (First 3 chunks):**
{docs_context}

**Evidence Summary:**
{evidence_context if evidence_context else "No evidence summary available"}

---

Now evaluate this draft answer according to the rubric above. Return strictly valid JSON only."""

        return prompt

    @staticmethod
    def _format_docs_context(docs: List[Any], max_docs: int = 3) -> str:
        """Format retrieved documents for prompt context."""
        if not docs:
            return "No documents retrieved."

        formatted = []
        for idx, doc in enumerate(docs[:max_docs], 1):
            try:
                content = doc.page_content if hasattr(doc, "page_content") else str(doc)
                metadata = doc.metadata if hasattr(doc, "metadata") else {}
                source = metadata.get("source", "Unknown") if metadata else "Unknown"
                header = metadata.get("header_path", "N/A") if metadata else "N/A"

                # Truncate long content
                preview = content[:200] + "..." if len(content) > 200 else content

                formatted.append(
                    f"[Doc {idx}] Source: {source} | Header: {header}\n"
                    f"Preview: {preview}"
                )
            except Exception as e:
                formatted.append(f"[Doc {idx}] Error formatting: {str(e)[:50]}")

        return "\n\n".join(formatted)

    @staticmethod
    def _parse_json(text: str) -> Dict[str, Any] | None:
        """Extract JSON from text, stripping markdown fences if present."""
        fence_match = re.search(r"```(?:json)?\s*(.*?)\s*```", text, re.DOTALL)
        if fence_match:
            text = fence_match.group(1)
        try:
            return json.loads(text.strip())
        except json.JSONDecodeError:
            return None

    @staticmethod
    def _fallback_critique() -> Dict[str, Any]:
        """Return safe fallback critique requesting revision."""
        return {
            "relevance_score": 0.5,
            "accuracy_score": 0.5,
            "completeness_score": 0.5,
            "coherence_score": 0.5,
            "format_score": 0.3,
            "overall_score": 0.47,
            "is_acceptable": False,
            "format_valid": False,
            "format_issues": ["Unable to evaluate - LLM parsing failed"],
            "critical_issues": ["Evaluation error - please regenerate"],
            "minor_issues": [],
            "strengths": [],
            "feedback": "An error occurred during evaluation. Please regenerate the answer.",
            "revision_required": True,
            "revision_focus": "Regenerate answer and ensure proper formatting",
        }


_agent = CriticAgent()


def critic_node(state: AgentState) -> Dict[str, Any]:
    """
    LangGraph node wrapper for the Critic Agent.

    This is the function registered with ``workflow.add_node("critic", critic_node)``.
    It delegates to a module-level ``CriticAgent`` singleton so the LLM client
    is initialized once and reused across invocations.

    Input (from AgentState):
        - user_query (str)
        - draft (str): From Generator
        - task_type (str): From Supervisor
        - retrieved_docs (List[Document]): From Retriever
        - evidence_summary (List[str]): From Retriever
        - revision_count (int): Incremented on each revision

    Output (merged into AgentState):
        - critique (dict): Evaluation results with scores and feedback
        - revision_required (bool): Whether answer needs revision
        - revision_count (int): Updated revision counter
        - final_answer (str): Finalized answer or empty for revision

    Decision Logic:
        - If format_valid = false → revision required (format is critical gate)
        - If overall_score < 0.75 → revision required
        - If revision_count >= MAX_REVISIONS → accept anyway (prevent infinite loop)
        - Otherwise → accept and finalize
    """
    return _agent(state)
